- README.md
merge if you feel it is of sufficient interest and quality.
> added my blog

- README.md
Under the Hood of .NET Memory Management - this great free ebook should be mentioned in the repo :)
> Added book

- README.md
Not sure if it's worth to be here. But it seems that guys from CoreCLR use it for performance test - [link](https://github.com/dotnet/coreclr/search?utf8=%E2%9C%93&q=Microsoft.Xunit.Performance)
> Add xunit.performance

- README.md
You can look at the benchmark
https://github.com/stebet/DependencyInjectorBenchmarks
> Added SimpleInjector

- README.md
Can we add prefix to the list? Thanks!
> Add prefix to the list

- README.md
Repo: https://github.com/alhardy/AppMetrics
Docs: https://alhardy.github.io/app-metrics-docs/getting-started/intro.html
> Adding App.Metrics to performance management

- README.md
The book Functional Concurrency in .NET covers techniques and design patterns to apply the functional paradigm for writing highly concurrent code
> Adding Functional Concurrency book title

- README.md
A proposal of the Conferences section and a link to the Pro .NET Memory Management book 🌶
> Dotnetos & Pro .NET Memory Management

- README.md
Add monitoring section
Add blog posts and conference sessions
> Update content 

- README.md
Updated "Writing High-Performance .NET Code" book link with new edition.
Adam thank's a lot for share this collection.
> Update "Writing High-Performance .NET Code" to second edition

- README.md
And reorder items to group all books from the "Pro .NET" Apress series together.
> Add book "Pro .NET Benchmarking"

- README.md
> Update DryIoc URL

- README.md
Add [Unchase.FluentPerformanceMeter](https://github.com/unchase/Unchase.FluentPerformanceMeter) open-source library.
Please consider to include.
> Add Unchase.FluentPerformanceMeter

- README.md
Hey @adamsitnik 
fixing two links to training courses.
Cheers!
> Fixing two links in the training section

- README.md
"AWS Lambda — Container Image .NET Benchmark" article is added.
> New article is added.

- README.md
Hi! Thanks for making this list!
I felt as if codetrack, a completely **free** tool, should be in it as well.
> Add codetrack to profilers

- README.md
I added publication dates to the books. Some books may be more or less useful to some developers depending on the publication. Feel free to pull this change if you think it would be useful to others.
> Added publication dates to the books section

- README.md
> Fixed dead links using web archive

- README.md
Add blog post.
https://samsaffron.com/archive/2011/10/28/in-managed-code-we-trust-our-recent-battles-with-the-net-garbage-collector
By Sam Saffron
> Add blog post by Sam Saffron

- README.md
Add a link to Performance improvements in .NET 6, and fix the title of a previous link.
> Add a link

- README.md
> Add link to background type preloading and mcj talk

- README.md
Came across this link in a twitter thread and noticed a lot of the blog posts referenced on my blog point to an old location, so this is just a quick PR to update the links
> update links to blog posts

- README.md
As discussed, I am adding .NET DSL contribution.
> Add Jmeter DSL for .NET

- README.md
add `Performance Improvements in .NET 8` blog post
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-8/
> add Performance Improvements in .NET 8 blog post
